// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/store-redesign/DarkGoldLuxury.tsx": () => import("../components/mockups/store-redesign/DarkGoldLuxury.tsx"),
  "./components/mockups/store-redesign/IvoryEditorial.tsx": () => import("../components/mockups/store-redesign/IvoryEditorial.tsx")
};
