/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin.session'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bespoke': typeof BespokeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/sale': typeof SaleRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bespoke': typeof BespokeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/sale': typeof SaleRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bespoke': typeof BespokeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/sale': typeof SaleRoute
  '/shop': typeof ShopRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bespoke'
    | '/cart'
    | '/checkout'
    | '/sale'
    | '/shop'
    | '/track'
    | '/wishlist'
    | '/product/$slug'
    | '/api/admin/login'
    | '/api/admin/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bespoke'
    | '/cart'
    | '/checkout'
    | '/sale'
    | '/shop'
    | '/track'
    | '/wishlist'
    | '/product/$slug'
    | '/api/admin/login'
    | '/api/admin/session'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bespoke'
    | '/cart'
    | '/checkout'
    | '/sale'
    | '/shop'
    | '/track'
    | '/wishlist'
    | '/product/$slug'
    | '/api/admin/login'
    | '/api/admin/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BespokeRoute: typeof BespokeRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  SaleRoute: typeof SaleRoute
  ShopRoute: typeof ShopRoute
  TrackRoute: typeof TrackRoute
  WishlistRoute: typeof WishlistRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BespokeRoute: BespokeRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  SaleRoute: SaleRoute,
  ShopRoute: ShopRoute,
  TrackRoute: TrackRoute,
  WishlistRoute: WishlistRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
